os: osx
osx_image: xcode10.1
language: java

before_install:
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew uninstall node
  - brew install node
  - rvm --default use 2.4.5
  - git clone https://github.com/nsilvestre/ToDoList.git

install:
  - npm install -g appium
  - brew upgrade carthage
  - gem install cocoapods
  - pod repo update
  - pod install

script:
  - xcodebuild -sdk iphonesimulator -workspace ToDoList.xcworkspace -scheme ToDoList -configuration Release clean build -derivedDataPath builddata/
  - appium &
  - mvn test
