os: osx
osx_image: xcode10.1
language: java

before_install:
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew uninstall node
  - brew install node

install:
  - npm install -g appium
  - brew upgrade carthage

script:
  - appium
  - mvn test